CREATE TABLE user (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,  
  name VARCHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  user_form VARCHAR(255) NOT NULL 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
